apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-pod1
  name: new-pod1
  namespace: wercker
spec:
  containers:
  - image: nginx
    name: new-pod1


---
apiVersion: v1
kind: Service
metadata:
  name: rest-simpleapp-svc
  namespace: wercker
spec:
  type: NodePort
  selector:
    run: new-pod1
  ports:
    - port: 8088
      targetPort: 80 
      nodePort: 31500    
